export const GET_STATUS = "GET_STATUS";
export const REGISTER_MOBILE_NUMBER = "REGISTER_MOBILE_NUMBER";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_IP_ADDRESS = "SET_IP_ADDRESS";

export const USER_REGISTERATION_STATUS = "USER_REGISTERATION_STATUS";

export const REGISTER_DISTRIBUTOR = 'REGISTER_DISTRIBUTOR';
